M48
; DRILL file KiCad 10.0.3 date 2026-08-11T23:50:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T23:50:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.778
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X104.856Y-30.666
X116.794Y-30.666
T2
X28.0Y-28.0
X28.0Y-184.0
X184.0Y-28.0
X184.0Y-184.0
M30
